# Generated by Django 4.0.2 on 2022-02-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nosology',
            fields=[
                ('idnosology', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.SlugField(max_length=128, unique=True)),
                ('nosologyname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nosology')),
            ],
            options={
                'verbose_name': 'Nosology',
                'verbose_name_plural': 'Nosologies',
            },
        ),
        migrations.CreateModel(
            name='Nosologydata',
            fields=[
                ('iddata', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=45, null=True)),
                ('valuetype', models.CharField(blank=True, max_length=45, null=True)),
                ('inpout', models.TextField(blank=True, null=True)),
                ('idnosology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nosologies.nosology')),
            ],
            options={
                'verbose_name': 'Nosologydata',
                'verbose_name_plural': 'Nosologydata',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('iduser', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.SlugField(max_length=128)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('idobserver', models.BigAutoField(primary_key=True, serialize=False)),
                ('val', models.CharField(blank=True, db_column='Val', max_length=45, null=True)),
                ('cortege', models.IntegerField(blank=True, db_column='Cortege', null=True)),
                ('idmodel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nosologies.nosologydata')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nosologies.patient')),
            ],
            options={
                'verbose_name': 'Observer',
                'verbose_name_plural': 'Observer',
                'get_latest_by': 'cortege',
            },
        ),
    ]
